cart/urls.py
"""Urls for cart app."""
from django.urls import path

from .views import CartPageView, cart_toggle, update_cart_offcanvas

urlpatterns = [
    path('your-cart/', CartPageView.as_view(), name='cart-list'),
    path('ajax/toggle/', cart_toggle, name='cart-toggle'),
    path('update_offcanvas/', update_cart_offcanvas, name='cart-offcanvas'),
]

checkout/urls.py
"""Url Patterns for the Checkout App."""
from django.urls import path

from .views import OrderCreateView, OrderDetailView, OrderListView, cache_data
from .webhooks import webhook

urlpatterns = [
    path('payment/', OrderCreateView.as_view(), name='order-create'),
    path('your-order/<int:pk>/',
         OrderDetailView.as_view(), name='order-detail'),
    path('your-orders/',
         OrderListView.as_view(), name='order-list'),
    path('cache_data/', cache_data, name='cache-data'),
    path('webhook/', webhook, name='webhook'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

# Handlers for custom error pages
handler404 = 'config.views.custom_page_not_found'
handler403 = 'config.views.custom_permission_denied'
handler400 = 'config.views.custom_bad_request'
handler500 = 'config.views.custom_server_error'

# Patterns for the shop section functions
shop_patterns = [
    path('', include(('products.urls', 'products'),
                     namespace='products')),
    path('cart/', include(('cart.urls', 'cart'),
                          namespace='cart')),
    path('checkout/', include(('checkout.urls', 'checkout'),
                              namespace='checkout')),
    path('likes/', include(('likes.urls', 'likes'),
                           namespace='likes'))
]

account_patterns = [
    # Allauth functions
    path('', include('allauth.urls')),
    path('', include(('users.urls', 'users'),
                     namespace='users')),
]

urlpatterns = [
    # Internationalization functions
    path('i18n/', include('django.conf.urls.i18n')),
    # Rich Text Editor functions
    path('tinymce/', include('tinymce.urls')),
    # Jasmine testing functions
    path('jasmine/', include(('jasmine_testing.urls', 'jasmine_testing'),
                             namespace='jasmine')),
    # My apps
    path('accounts/', include(account_patterns)),
    path('contact-us/', include(('contact.urls', 'contact'),
                                namespace='contact')),
    path('cookies/', include(('cookies.urls', 'cookie'),
                             namespace='cookies')),
    path('', include(('info.urls', 'info'),
                     namespace='info')),
    path('policies/', include(('policies.urls', 'policies'),
                              namespace='policies')),
    path('shop/', include(shop_patterns)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
)

products/urls.py
"""Urls for the contact module."""
from django.urls import path

from .views import ProductDetailView, ProductListView, ShopCategoryDetailView

urlpatterns = [
    path('', ProductListView.as_view(), name='product-list'),
    path('category/<slug:slug>-<int:pk>/', ShopCategoryDetailView.as_view(),
         name='shop-category-detail'),
    path('product/<slug:slug>-<int:pk>/', ProductDetailView.as_view(),
         name='product-detail'),
]

pwa/urls.py
"""Urls for the pwa module."""
from django.urls import path

from .views import SWTemplateView, render_offline

urlpatterns = [
    # Service Worker Template string
    path('sw.js',
         SWTemplateView.as_view(), name='service-worker'),
    path('offline/',
         render_offline, name='offline'),
]

cart/views.py
"""Views for cart app: a page for viewing items in the cart
and fetch views to update cart and update the template."""

from django.http import HttpResponseForbidden, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.template import RequestContext
from django.utils.translation import ugettext_lazy as _
from django.views.generic.base import TemplateView

from products.models import Product

from .context_processors import get_cart


class CartPageView(TemplateView):  # pylint: disable=too-many-ancestors
    """View that displays all the products in the cart as a list."""
    template_name = 'cart/cart_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        products = Product.objects.filter(
            stock__gte=1, display=True
        ).order_by('-popularity', '-stock') | Product.objects.filter(
            can_preorder=True, display=True
        ).order_by('-popularity', '-stock')

        context['related_products'] = products

        return context


def cart_toggle(request):
    """Add or removes the specified product to the shopping cart.
    The view is Fetch, so it is only called by a JS file.
    It runs through numerous variables such as item stock,
    whether the item is unique, etc, before giving a response.
    The decorator converts the response to JSON format.
    It is then picked up by the JS file which completes the page effects.
    'tag' and 'message' are used to display the toasts.
    'result' and 'special' are used to define the logic on the JS side."""

    data = {}
    if request.method == "POST":
        # Runs through a number of variables to process the ajax call.
        # If it fails, it throws an exception with a message.
        try:
            # Tries to retrieve the item and quantity,
            # if no item was given it is set to '0' to throw an error.
            item_id = request.POST.get('item-id', '0')
            product = get_object_or_404(Product, pk=item_id)
            quantity = int(request.POST.get('quantity'))

            # Gets the cart to run through item details.
            cart = request.session.get('cart', {})

            # Removes items from the cart if it is a once-off unique item or
            # if the remove button is clicked on the cart list page.
            if (item_id in list(cart.keys()) and request.POST.get(
                'special') != 'update') or (
                    request.POST.get('special') == 'remove') or (
                    quantity <= 0):
                if item_id in cart:
                    cart.pop(str(item_id))
                    data['message'] = _(
                        f'Removed {product.title} from your cart.')
                else:
                    data['message'] = _(
                        f'Please update the quantity to add \
                            {product.title} to your cart.')

                request.session['cart'] = cart
                data['tag'] = 'info'
                data['tagMessage'] = _('Info')

            # If the other conditions aren't true it is a simple add to cart.
            else:
                if product.is_unique:
                    quantity = 1
                elif (quantity > product.stock
                      and not product.can_preorder):
                    quantity = product.stock

                if (request.POST.get('special') == 'update') and (
                        item_id in cart):
                    # 'update' is sent when product quantity is being changed.
                    data['message'] = f'Updated {product.title} \
                        quantity to {quantity}.'
                elif product.can_preorder and product.stock <= 0:
                    data['message'] = _(
                        f'Preordered {quantity} {product.title}.')
                else:
                    data['message'] = _(
                        f'Added {quantity} {product.title} to your cart.')

                cart[item_id] = quantity
                request.session['cart'] = cart

                data['tag'] = 'success'
                data['tagMessage'] = _('Success')

            # Calculates the grand total and
            # then pushes all details into the context.
            RequestContext(request).push(get_cart(request))

            cart_quantity = request.session.get('cart_quantity', 0)
            cart_total = request.session.get('cart_total', '0.00')
            delivery = request.session.get('delivery', '0.00')
            grand_total = request.session.get('grand_total', '0.00')

            request.session['cart_quantity'] = cart_quantity
            request.session['cart_total'] = cart_total
            request.session['delivery'] = delivery
            request.session['grand_total'] = grand_total

            data['result'] = ['cart',
                              cart_quantity,
                              cart_total,
                              delivery,
                              grand_total]

        # If none of the conditions are true, it throws an error.
        except Exception as error:  # pylint: disable=broad-except
            # Calculates the grand total and
            # then pushes all details into the context.
            RequestContext(request).push(get_cart(request))
            data['message'] = _(f'Error adding item to cart: {error}')
            data['result'] = 'error'
            data['tag'] = 'danger'
            data['tagMessage'] = _('Error')

        return JsonResponse(data)
    return HttpResponseForbidden()


def update_cart_offcanvas(request):
    """This view is used to update the cart_popover.html template.
    It is called by the JS file after it successfully receives
    the cart_toggle view response.
    It updates the context using the same logic as the get_cart context
    processor before refreshing the template.
    The JS script then pushes the newly rendered template into
    the popover HTML."""

    # Re-renders the popover template
    return render(request, 'cart/includes/cart_offcanvas.html')

templates/cart/includes/box_cart_toggle.html
{% load static %}
<!--This is the button that appears on the product_box.html template.
The toggle-form class makes it a target for the ajax functions..-->
<form class="toggle-form d-inline-block" id="cf-{{ product.id }}" action="{% url 'cart:cart-toggle' %}" method="POST">
    <!--Selects the default icon based on whether the item is in the cart or not.
    object tags are used to display the SVG for caching.-->
    <button type="submit" class="toggle-submit product btn text-center rounded-circle shadow m-1 p-2"
        id="cb-{{ product.id }}">
        {% if product.id|stringformat:'s' in cart %}
        {% include 'base/includes/icons/cart-check-fill.svg' %}
        {% else %}
        {% include 'base/includes/icons/cart-plus.svg' %}
        {% endif %}
    </button>
    {% csrf_token %}
    <!--It only sends the product ID and always a quantity of 1.-->
    <input id="cq-{{ product.id }}" type="hidden" name="quantity" value="1" />
    <input type="hidden" name="item-id" value="{{ product.id }}" />
</form>

templates/cart/includes/cart_menu.html
<!-- Loads internationalization and static -->
{% load i18n %}
<button type="button"
    class="quantity-button position-relative btn btn-link d-inline-block text-white px-2 py-auto pb-md-1" tabindex="0"
    data-bs-toggle="offcanvas" data-bs-target="#offcanvasCart" aria-controls="offcanvasCart">
    <span class="visually-hidden">{% trans 'View Cart' %}</span>
    <!--Selects the default icon based on whether there are likes or not.-->
    {% include 'base/includes/icons/cart-fill.nav.svg' %}
    <span class="text-success position-absolute top-50 start-50 translate-middle m-0" data-bs-target="#offcanvasCart">
        <strong data-bs-target="#offcanvasCart"
            class="quantity-badge bg-white rounded-circle">{% if cart_quantity > 0 %}{{ cart_quantity }}{% endif %}</strong>
    </span>
</button>

templates/cart/includes/cart_offcanvas.html
<!-- Loads internationalization -->
{% load i18n %} {% load static %}
{% if cart %}
<div class="offcanvas-header pb-0">
    <h2 class="h-font h3 l-space-1 text-primary text-uppercase mx-auto" id="offcanvasCartLabel">{% trans 'Your Cart' %}
    </h2>
    <button type="button" class="btn-close text-reset ms-0" data-bs-dismiss="offcanvas" aria-label="Close"></button>
</div>
<div class="offcanvas-body">
    <div class="w-100 text-center mb-3">
        <a class="p-font smooth-click col-8 btn btn-success text-white shadow fw-bold mx-auto mb-0"
            href="{% url 'cart:cart-list' %}">{% trans 'Go to Cart' %}</a>
        <div class="col-12 my-2"></div>
        <a class="p-font col-8 smooth-click btn btn-info text-white shadow fw-bold mx-auto mb-0"
            href="{% url 'checkout:order-create' %}">{% trans 'Checkout' %}</a>
    </div>
    <ul class="list-group list-group-flush">
        {% for item in cart_items %}
        <li class="list-group-item list-group-item-action">
            <a href="{% url 'products:product-detail' item.product.slug item.product.id %}" class="p-font fs-6 mb-0">
                <img class="product-thumb col-2 d-inline-block float-start" src="{{ item.product.image_4_3_xs.url }}"
                    alt="{{ item.product.title }}">
                <div class="col-10 ms-auto">
                    <div class="row">
                        <span
                            class="col-9 text-decoration-underline text-truncate align-self-start ps-2">{{ item.product.title }}</span>
                    </div>
                    <div class="row mt-3">
                        <span class="col-auto text-muted align-self-end ms-auto">{{ item.quantity }} x
                            €{{ item.product.price }}</span>
                    </div>
                </div>
            </a>
        </li>
        {% endfor %}
        {% if delivery != 0 %}
        <li class="list-group-item list-group-item-action">
            <a class="p-font text-primary fs-6 mx-0 mb-0" href="{% url 'cart:cart-list' %}">
                <span class="float-start">{% trans 'Delivery' %}</span>
                <span class="float-end text-muted">€{{ delivery|floatformat:2 }}</span>
            </a>
        </li>
        {% endif %}
        <li class="list-group-item list-group-item-action">
            <a class="p-font text-primary fs-6 mx-0 mb-0" href="{% url 'cart:cart-list' %}">
                <strong><span class="float-start p-font">{% trans 'Total' %}</span></strong>
                <span class="float-end">€{{ grand_total }}</span>
            </a>
        </li>
    </ul>
</div>
{% else %}
<div class="offcanvas-header pb-0">
    <h2 class="h-font h3 l-space-1 text-primary text-uppercase mx-auto" id="offcanvasCartLabel">{% trans 'Empty Cart' %}
    </h2>
    <button type="button" class="btn-close text-reset ms-0" data-bs-dismiss="offcanvas" aria-label="Close"></button>
</div>
<div class="offcanvas-body">
    <div class="w-100 text-center mb-3">
        <a class="p-font col-8 btn-tran smooth-click btn btn-warning text-primary shadow fw-bold mx-auto mb-0"
            href="{% url 'products:product-list' %}">{% trans 'What can we offer you' %}?</a>
    </div>
</div>
{% endif %}

templates/cart/includes/cart_product_display.html
<!-- Loads internationalization, loads static  -->
{% load i18n %} {% load static %}
<!--Template used to display cart items in the cart_list.html template.-->
<li id="cart-item-{{ item.product.id }}" class="list-group-item p-3">
    <section class="row">
        <!--Provides an image with a link to the product.
        the cart-thumb class controls the size.-->
        <div class="col-2 py-0">
            <a href="{% url 'products:product-detail' item.product.slug item.product.id %}" class="smooth-click mb-0">
                <img src="{{ item.product.image_4_3_sm.url }}" class="img-fluid" alt="{{ item.product.title }}" />
            </a>
        </div>
        <div class="col-6 col-md-7 col-lg-8 position-relative ps-2">
            <div class="row">
                <!--Displays the item name, truncating longer text on smaller devices.-->
                <a class="smooth-click" href="{% url 'products:product-detail' item.product.slug item.product.id %}">
                    <h3 class="h-font l-space-1 text-primary text-truncate fs-6 fs-sm-5 fs-md-3">
                        {{ item.product.title|upper }}
                    </h3>
                </a>
                <div class="p-font d-none d-md-block d-lg-none text-primary mb-1">
                    {{ item.product.description|truncatechars:'70'|safe }}
                </div>
                <div class="p-font d-none d-lg-block text-primary mb-1">
                    {{ item.product.description|truncatechars:'120'|safe }}
                </div>
            </div>
            <!-- Displays the product description and the button layout on larger screens.-->
            <form class="toggle-form row w-100 align-items-end" id="af-{{ item.product.id }}"
                action="{% url 'cart:cart-toggle' %}" method="POST">
                {% csrf_token %}
                <div class="col-9 col-sm-6 col-md-4">
                    <div class="form-floating">
                        <input class="form-control d-inline-block" type="number" id="cq-{{ item.product.id }}"
                            name=" quantity" value="{{ item.quantity }}" min="1" {% if item.product.stock > 0 %}
                            max="{{ item.product.stock }}" {% endif %} required{% if item.product.is_unique %}
                            readonly{% endif %} />
                        <label class="p-font text-primary sr-only requiredField"
                            for="cq-{{ item.product.id }}">{% trans 'Quantity' %}</label>
                    </div>
                </div>
                <div class="col-12 d-md-none"></div>
                <!--Shows buttons appropriately based on item type.
                    Items can be removed from the cart.
                    Allows for quantity to be updated if there is numerous stock.-->
                <div class="col-6 col-sm-3 col-md-4 col-lg-3 col-xl-2 text-center mt-2 mt-md-0 ps-md-2">
                    <button id="cb-{{ item.product.id }}" type="submit"
                        class="update-button p-font btn btn-sm btn-success fw-bold shadow">{% trans 'Update' %}</button>
                </div>
                <div class="col-6 col-sm-3 col-md-4 col-lg-3 col-xl-2 text-center">
                    <button id="re-{{ item.product.id }}" type="submit"
                        class="remove-button p-font btn btn-sm btn-link text-danger">{% trans 'Remove' %}</button>
                </div>
                <input type="hidden" name="item-id" value="{{ item.product.id }}" />
            </form>
        </div>
        <div class="col-4 col-md-auto text-end ms-auto me-md-2">
            <p class="p-font text-muted h5">€{{ item.product.price }}</p>
        </div>
    </section>
</li>

templates/cart/includes/cart_total.html
<!-- Loads internationalization  -->
{% load i18n %}
<!--A template which displays the cart total and delivery cost on the cart_list page.-->
<li class="list-group-item">
    <div class="row">
        <div class="col-2 d-none d-md-block"></div>
        <div class="col-auto px-md-2">
            <p class="p-font text-primary fs-5"><strong>{% trans 'Cart Total' %}:</strong></p>
        </div>
        <!--Displays the current delivery total.-->
        <div class="col-auto text-end ms-auto">
            <p class="p-font l-space-1 text-primary fs-5"><strong id="cart-items"
                    class="cart-totals">€{{ cart_total }}</strong></p>
        </div>
    </div>
</li>

templates/cart/includes/detail_cart_toggle.html
<!-- Loads internationalization -->
{% load i18n %}
<!--This is the button that appears on the product_detail.html template.
The toggle-form class makes it a target for the ajax functions.
If the item has numerous stock option the product_detail.html template displays a quantity selection box.
This box is linked to this form and does not appear in this template.-->
<form class="toggle-form col-9 col-md-10 col-lg-9 pl-0 " id="cf-{{ product.id }}" action="{% url 'cart:cart-toggle'%}"
    method="POST">
    <button type="submit" id="cb-{{ product.id }}"
        class="p-font product-detail-color fs-6 btn btn-lg btn-success shadow w-100">
        <!--Selects the default icon based on whether the item is in the like context or not.
                object tags are used to display the SVG for caching.-->
        {% if product.id|stringformat:'s' in cart %}
        {% include 'base/includes/icons/cart-check-fill.svg' %}
        &nbsp;&nbsp;{% trans 'Update Cart' %}
        {% else %}
        {% include 'base/includes/icons/cart-plus.svg' %}
        &nbsp;&nbsp;{% trans 'Add to Cart' %}
        {% endif %}
    </button>
    {% csrf_token %}
    <!--Always sends the product id.
    If the product is unique it automatically sends 1 as the quantity.
    It send the 'special=stocked' value for other items for logic in the ajax JS and views.-->
    <input type="hidden" name="item-id" value="{{ product.id }}" />
    <input type="hidden" name="special" value="update" />
</form>

templates/cart/includes/subtotal.html
<!-- Loads internationalization  -->
{% load i18n %}
<article class="col-12 col-md-4 order-0 order-md-1">
    <div class="subtotal-card card position-md-sticky border-0">
        <div class="card-body">
            {% if deliver != 0 %}
            <div class="d-flex justify-content-between">
                <p class="p-font card-subtitle mb-2 text-muted h5">{% trans 'Delivery' %}:</p>
                <p id="cart-delivery" class="p-font cart-totals card-subtitle mb-2 text-muted h5">
                    €{{ delivery|floatformat:2 }}</p>
            </div>
            {% endif %}
            <div class="d-flex justify-content-between">
                <h3 class="p-font card-title text-primary h4">{% trans 'Sub-total' %}:</h3>
                <h3 id="cart-grand" class="p-font cart-totals card-title text-primary h4">€{{ grand_total }}</h3>
            </div>
            <p class="p-font fs-6 text-muted card-text">
                {% if delivery != 0 %}
                {% trans 'Delivery will be calculated at the checkout' %}.<br><br>
                {% endif%}
                {% trans 'Thank you so much for supporting a small business' %}.
            </p>
            <div class="text-end text-md-start">
                <a class="p-font smooth-click btn btn-info text-white shadow fw-bold mb-0"
                    href="{% url 'checkout:order-create' %}">{% trans 'Proceed with Order' %}</a>
            </div>
        </div>
    </div>
</article>