cart/urls.py
"""Urls for cart app."""
from django.urls import path

from .views import CartPageView, cart_toggle, update_cart_offcanvas

urlpatterns = [
    path('your-cart/', CartPageView.as_view(), name='cart-list'),
    path('ajax/toggle/', cart_toggle, name='cart-toggle'),
    path('update_offcanvas/', update_cart_offcanvas, name='cart-offcanvas'),
]

checkout/urls.py
"""Url Patterns for the Checkout App."""
from django.urls import path

from .views import OrderCreateView, OrderDetailView, OrderListView, cache_data
from .webhooks import webhook

urlpatterns = [
    path('payment/', OrderCreateView.as_view(), name='order-create'),
    path('your-order/<int:pk>/',
         OrderDetailView.as_view(), name='order-detail'),
    path('your-orders/',
         OrderListView.as_view(), name='order-list'),
    path('cache_data/', cache_data, name='cache-data'),
    path('webhook/', webhook, name='webhook'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

# Handlers for custom error pages
handler404 = 'config.views.custom_page_not_found'
handler403 = 'config.views.custom_permission_denied'
handler400 = 'config.views.custom_bad_request'
handler500 = 'config.views.custom_server_error'

# Patterns for the shop section functions
shop_patterns = [
    path('', include(('products.urls', 'products'),
                     namespace='products')),
    path('cart/', include(('cart.urls', 'cart'),
                          namespace='cart')),
    path('checkout/', include(('checkout.urls', 'checkout'),
                              namespace='checkout')),
    path('likes/', include(('likes.urls', 'likes'),
                           namespace='likes'))
]

account_patterns = [
    # Allauth functions
    path('', include('allauth.urls')),
    path('', include(('users.urls', 'users'),
                     namespace='users')),
]

urlpatterns = [
    # Internationalization functions
    path('i18n/', include('django.conf.urls.i18n')),
    # Rich Text Editor functions
    path('tinymce/', include('tinymce.urls')),
    # Jasmine testing functions
    path('jasmine/', include(('jasmine_testing.urls', 'jasmine_testing'),
                             namespace='jasmine')),
    # My apps
    path('accounts/', include(account_patterns)),
    path('contact-us/', include(('contact.urls', 'contact'),
                                namespace='contact')),
    path('cookies/', include(('cookies.urls', 'cookie'),
                             namespace='cookies')),
    path('', include(('info.urls', 'info'),
                     namespace='info')),
    path('policies/', include(('policies.urls', 'policies'),
                              namespace='policies')),
    path('shop/', include(shop_patterns)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
)

policies/urls.py
"""Urls for the policy module."""
from django.urls import path

from .views import PolicyDetailView

urlpatterns = [
    path('policy/<slug:slug>-<int:pk>/', PolicyDetailView.as_view(),
         name='policy-detail'),
]

products/urls.py
"""Urls for the contact module."""
from django.urls import path

from .views import ProductDetailView, ProductListView, ShopCategoryDetailView

urlpatterns = [
    path('', ProductListView.as_view(), name='product-list'),
    path('category/<slug:slug>-<int:pk>/', ShopCategoryDetailView.as_view(),
         name='shop-category-detail'),
    path('product/<slug:slug>-<int:pk>/', ProductDetailView.as_view(),
         name='product-detail'),
]

pwa/urls.py
"""Urls for the pwa module."""
from django.urls import path

from .views import SWTemplateView, render_offline

urlpatterns = [
    # Service Worker Template string
    path('sw.js',
         SWTemplateView.as_view(), name='service-worker'),
    path('offline/',
         render_offline, name='offline'),
]

checkout/views.py
"""Views for the checkout.
Creating, listing and showing order details. Also caches info."""
import itertools
import json
import logging

import stripe
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import CharField, model_to_dict
from django.shortcuts import HttpResponse, redirect, reverse
from django.utils import translation
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.http import require_POST
from django.views.generic import CreateView, DetailView, ListView
from phonenumber_field import widgets

from cart.context_processors import get_cart
from policies.models import Policy
from products.models import Product

from .models import Order, OrderLineItem


class OrderDetailView(DetailView):
    """Displays the details for an Order object.
    It doesn't require login as Anonymous users must utilise the view. However,
    it will check if the current user is the user who made the order.
    If an anonymous user has made an order, they should have their order ID
    stored in their session and can access the order that way."""

    model = Order
    context_object_name = 'order'

    def dispatch(self, *args, **kwargs):
        """Checks to make sure that the user trying to access the page is the
        same user that has made the order before the page is accessed."""

        # Gets the user and the Order object
        user = self.request.user
        this_object = self.get_object()

        # Checks to see whether the user is logged in or has the
        # necessary session cookie. If not, they are redirected.
        if user.is_authenticated:
            userprofile = self.request.user.userprofile
            # Checks to see if the user has made this order, else redirects:
            if this_object.user_profile == userprofile:
                return super().dispatch(*args, **kwargs)
        elif 'my_order' in self.request.session:
            # Checks to see if the user has the correct order in the session:
            if self.request.session['my_order'] == this_object.id:
                return super().dispatch(*args, **kwargs)

        return redirect(reverse('products:product-list'))


class OrderListView(LoginRequiredMixin, ListView):  # noqa E501  # pylint: disable=too-many-ancestors
    """Displays all Orders made by a user in reverse chronological order.
    It requires login as anonymous users can't access
    more than one order at a time."""

    model = Order
    context_object_name = 'orders'
    ordering = ['-date']
    paginate_by = 10

    def get_queryset(self):
        """Filters the Order to those made only by this user."""
        userprofile = self.request.user.userprofile
        return Order.objects.filter(user_profile=userprofile).order_by('-date')


class OrderCreateView(CreateView):
    """Creates an Order on payment completion.
    Uses custom form widgets and layouts."""

    model = Order
    fields = ['email', 'billing_full_name', 'billing_phone_number',
              'billing_street_address_1', 'billing_street_address_2',
              'billing_town_or_city', 'billing_county',
              'billing_country', 'billing_postcode', 'shipping_full_name',
              'shipping_phone_number', 'shipping_street_address_1',
              'shipping_street_address_2', 'shipping_town_or_city',
              'shipping_county', 'shipping_country', 'shipping_postcode']

    def get_form(self, form_class=None):
        """Adds custom placeholders and widgets to the form"""
        form = super().get_form(form_class)
        form.fields['email'].widget.attrs = {'placeholder': _('Email Address')}
        form.fields['email'].label = _('Email')
        form.fields['shipping_full_name'].widget.attrs = {
            'placeholder': _('Full Name')}
        form.fields['shipping_full_name'].label = _('Full Name')
        form.fields['shipping_phone_number'] = CharField(
            widget=widgets.PhoneNumberPrefixWidget(
                attrs={
                    'type': 'tel',
                    'placeholder': _('Phone Number'),
                    'class': 'form-control',
                    'pattern': '[0-9]+',
                }),
            initial='+39')
        form.fields['shipping_street_address_1'].widget.attrs = {
            'placeholder': _('123 Main St.')}
        form.fields['shipping_street_address_1'].label = _('Street Address 1')
        form.fields['shipping_street_address_2'].widget.attrs = {
            'placeholder': _('Street Address 2')}
        form.fields['shipping_street_address_2'].label = _('Street Address 2')
        form.fields['shipping_town_or_city'].widget.attrs = {
            'placeholder': _('Town or City')}
        form.fields['shipping_town_or_city'].label = _('Town or City')
        form.fields['shipping_county'].widget.attrs = {
            'placeholder': _('Locality')}
        form.fields['shipping_county'].label = _('County, State or Locality')
        form.fields['shipping_country'].widget.attrs = {
            'class': 'form-control'}
        form.fields['shipping_country'].label = _('Country')
        form.fields['shipping_postcode'].widget.attrs = {
            'placeholder': _('Postcode')}
        form.fields['shipping_postcode'].label = _('Postcode')
        form.fields['billing_full_name'].widget.attrs = {
            'placeholder': _('Full Name'), 'class': 'billing-field'}
        form.fields['billing_full_name'].label = _('Full Name')
        form.fields['billing_phone_number'] = CharField(
            label=_('Phone Number'),
            widget=widgets.PhoneNumberPrefixWidget(
                attrs={
                    'type': 'tel',
                    'placeholder': _('Phone Number'),
                    'class': 'form-control billing-field',
                    'pattern': '[0-9]+',
                }),
            initial='+39')
        form.fields['billing_street_address_1'].widget.attrs = {
            'Placeholder': _('Street Address 1'), 'class': 'billing-field'}
        form.fields['billing_street_address_1'].label = _('Street Address 1')
        form.fields['billing_street_address_2'].widget.attrs = {
            'placeholder': _('Street Address 2')}
        form.fields['billing_street_address_2'].label = _('Street Address 2')
        form.fields['billing_town_or_city'].widget.attrs = {
            'placeholder': _('Town or City'), 'class': 'billing-field'}
        form.fields['billing_town_or_city'].label = _('Town or City')
        form.fields['billing_county'].widget.attrs = {
            'placeholder': _('Locality')}
        form.fields['billing_county'].label = _('County, State or Locality')
        form.fields['billing_country'].widget.attrs = {
            'class': 'form-control billing-field'}
        form.fields['billing_country'].label = _('Country')
        form.fields['billing_postcode'].widget.attrs = {
            'placeholder': _('Postcode')}
        form.fields['billing_postcode'].label = _('Postcode')
        return form

    def dispatch(self, *args, **kwargs):
        """Checks for items in cart and redirects to the home page if there
        aren't any."""

        cart = self.request.session.get('cart', {})
        if not cart:
            messages.info(self.request, _('The cart is empty.'))
            return redirect(reverse('products:product-list'))
        return super().dispatch(*args, **kwargs)

    def get_initial(self):
        """If the user is logged in, it sets the initial form values
        to the values in their user profile."""

        initial = super().get_initial()
        if self.request.user.is_authenticated:
            # Gets the UserProfile and makes it a dictionary
            user = self.request.user
            userprofile = user.userprofile
            userprofile_dict = model_to_dict(userprofile)

            # Iterates the fields, sets the email separately, and fills others.
            for field, key in itertools.product(self.fields, userprofile_dict):
                if field == 'email':
                    initial['email'] = user.email
                elif field == key:
                    initial[f'{field}'] = userprofile_dict[key]
            return initial
        return initial

    def form_valid(self, form):
        """If the form is valid it adds additional information to the form
        before saving the Order, such as Stripe PID, the original cart for
        reference and billing/shipping info.
        If an invalid item is somehow in the cart, it removes the order.
        It will delete the cart in the session.
        Attaches the user tot he order if logged in or adds a the order to the
        session so an anonymous user can access the Order Detail Page."""

        # Saves the form but doesn't commit it to the database yet.
        order = form.save(commit=False)
        # Fills in the STRIPE PID in
        pid = self.request.POST.get('client_secret').split('_secret')[0]
        order.stripe_pid = pid
        # Dumps the original cart info
        cart_contents = get_cart(self.request)
        cart = cart_contents['cart']
        order.original_cart = json.dumps(cart)
        order.delivery_cost = cart_contents['delivery']
        # If billing and shipping info are the marked as the same, it fills in
        # the billing with the POST data. Clauses are used for optional info.
        if 'billing-same' in self.request.POST:
            order.billing_full_name = self.request.POST['shipping_full_name']
            order.billing_phone_number = self.request.POST[
                'shipping_phone_number_0'] + self.request.POST[
                    'shipping_phone_number_1']
            order.billing_street_address_1 = self.request.POST[
                'shipping_street_address_1']
            if 'shipping_street_address_2' in self.request.POST:
                order.billing_street_address_2 = self.request.POST[

templates/checkout/order_form.html
{% extends 'base/base.html' %}

{% load static %}{% load i18n %}

<!-- Meta details -->
{% block meta_description %}{% trans 'Thank you for your exchange and your support.' %}{% endblock %}
{% block meta_keywords %}{{ block.super }} {% trans 'checkout, payment' %}{% endblock %}

<!--  Open Graph -->
{% block og_type %}website{% endblock %}
{% block og_title %}{% trans 'Ancient Wisdom, Modern Healing' %}{% endblock %}
{% block og_description %}{% trans 'Consciousness, spirituality, healing and ancestry. Working with systems such as Tarot, Oracle Cards, Shamanic Drumming and Healing. Creating events for sharing and connections between individuals and cultures.' %}{% endblock %}
{% block og_image %}{{request.scheme}}://{{request.META.HTTP_HOST}}{% static 'open_graph/logo1200x630.png' %}{% endblock %}
{% block og_image_type %}image/png{% endblock %}
{% block og_image_width %}1200{% endblock %}
{% block og_image_height %}630{% endblock %}
{% block og_image_alt %}{% trans 'Nuragic Shamanic Healing Logo' %}{% endblock %}
{% load crispy_forms_tags %}
{% block head_title %}{% trans 'Checkout' %}{% endblock%}

{% block content %}
<nav class="col-12 bg-brown ps-3 py-1 py-sm-2 py-md-3" aria-label="breadcrumb">
    <ol class="breadcrumb mb-0">
        <li class="breadcrumb-item" aria-current="page">
            <a class="p-font smooth-click text-white" href="{% url 'cart:cart-list' %}">{% trans 'Cart' %}</a>
        </li>
        <li class="p-font text-secondary breadcrumb-item active" aria-current="page">{% trans 'Checkout' %}</li>
    </ol>
</nav>
{% if cart %}
<!--Displays content if there are items in the cart, else it shows a link to the home page.-->
<article class="row bg-white">
    <h2 class="visually-hidden">{% trans 'Checkout'%}</h2>
    <section class="col-12 col-md-6 order-2 order-md-1 p-2 p-md-4">
        <h3 class="visually-hidden">{% trans 'Payment Form'%}</h3>
        <form id="payment-form" action="{% url 'checkout:order-create' %}" method="POST">
            {% csrf_token %}
            <!--Displays the details for shipping. Give the option to mark billing details as the same.
            The info is pre-filled if it is saved to a user account.-->
            <fieldset class="input-style row mb-3">
                <legend class="p-font text-primary">{% trans 'Personal Details' %}</legend>
                {{ order_form.email|as_crispy_field }}
                {{ order_form.shipping_full_name|as_crispy_field }}
                {% with order_form.shipping_phone_number as field %}
                {% include 'bootstrap4/phone_field.html' %}
                {% endwith %}
            </fieldset>
            <fieldset class="input-style row">
                <legend class="p-font text-primary">{% trans 'Delivery Information' %}</legend>
                {{ order_form.shipping_street_address_1|as_crispy_field }}
                {{ order_form.shipping_street_address_2|as_crispy_field }}
                {{ order_form.shipping_town_or_city|as_crispy_field }}
                {{ order_form.shipping_county|as_crispy_field }}
                {{ order_form.shipping_postcode|as_crispy_field }}
                {{ order_form.shipping_country|as_crispy_field }}
                <div class="form-check my-2">
                    <!--Used to hide the section of the form below and
                    Javascript adds or removes the required attribute.-->
                    <input class="form-check-input" type="checkbox" id="billing-same" name="billing-same" checked />
                    <label class="p-font text-primary form-check-label"
                        for="billing-same">{% trans 'My billing details are the same as delivery.' %}</label>
                </div>
            </fieldset>
            <!--The id hidden-form-details is used to hide this section by default.
            Javascript will hide this and also declare the fields required or not required depending.-->
            <fieldset id="hidden-form-details" class="input-style row mb-3">
                <legend class="p-font text-primary">{% trans 'Billing Information' %}</legend>
                {{ order_form.billing_full_name|as_crispy_field }}
                {% with order_form.billing_phone_number as field %}
                {% include 'bootstrap4/phone_field.html' %}
                {% endwith %}
                <div class="mt-3"></div>
                {{ order_form.billing_street_address_1|as_crispy_field }}
                {{ order_form.billing_street_address_2|as_crispy_field }}
                {{ order_form.billing_town_or_city|as_crispy_field }}
                {{ order_form.billing_county|as_crispy_field }}
                {{ order_form.billing_postcode|as_crispy_field }}
                {{ order_form.billing_country|as_crispy_field }}
            </fieldset>
            <div class="input-style form-check mb-2">
                {% if user.is_authenticated %}
                <input class="form-check-input" type="checkbox" id="id-save-info" name="save-info" />
                <label class="p-font text-primary form-check-label"
                    for="id-save-info">{% trans 'Save these shipping and billing addresses to my profile' %}</label>
                {% else %}
                <a class="p-font text-info" href="{% url 'account_signup' %}">{% trans 'Create an account' %}</a>
                {% trans 'or' %} <a class="p-font text-info" href="{% url 'account_login' %}">{% trans 'login' %}</a>
                {% trans 'to save this information.' %}
                {% endif %}
            </div>
            <fieldset>
                <legend class="p-font h6 text-primary w-auto"><strong>{% trans 'Payment' %}*</strong>&nbsp;&nbsp; <a
                        target="_blank" rel="noopener"
                        href="https://stripe.com/">{% include 'base/includes/icons/stripepayments.svg'%}</a></legend>
                <!-- A Stripe card element will go here -->
                <div class="mb-3 form-control p-3" id="card-element"></div>
                <!-- Used to display form errors -->
                <div class="mb-3 text-danger" id="card-errors" role="alert"></div>
                <!-- Pass the client secret to the view so we can get the payment intent id -->
                <input type="hidden" value="{{ client_secret }}" name="client_secret" />
            </fieldset>
            <button type="submit" id="payment-submit"
                class="p-font text-white btn btn-info shadow fw-bold mb-2" disabled>{% trans 'Confirm Purchase' %}</button>
        </form>
        <p class="p-font text-muted small mb-1">
            *{% trans 'All of your payment details are processed by Stripe. We do not process or store your payment information.' %}
        </p>
        <p class="p-font text-muted small mb-0">{% trans 'By clicking "Confirm Purchase" you agree to our' %} <a
                class="text-info text-decoration-underline"
                href="{% url 'policies:policy-detail' active_returns.slug active_returns.id %}">{{active_returns.name }}</a>
            {% trans 'and' %} <a class="text-info text-decoration-underline"
                href="{% url 'policies:policy-detail' active_terms.slug active_terms.id %}">{{ active_terms.name }}</a>.
        </p>
    </section>
    <section class="col-12 col-md-6 order-1 order-md-2 p-2 p-md-4">
        <!-- Displays each item in the cart in rows.-->
        <h2 class="p-font text-primary fs-4">{% trans 'Items' %}</h2>
        <ul class="list-group list-group-flush">
            <li class="d-md-none list-group-flush" data-bs-toggle="collapse" data-bs-target="#itemSummary"
                aria-controls="itemSummary" aria-expanded="false">
                <button class="p-font d-md-none btn btn-link text-start text-info p-0">{% trans 'Details' %}
                    &#8595;</button>
            </li>
            <li id="itemSummary" class="list-group-flush collapse d-md-none ">
                <ul class="list-group-flush ps-0">
                    {% for item in cart_items %}
                    {% include 'checkout/includes/checkout_product_display.html' %}
                    {% endfor %}
                </ul>
            </li>
            <li class="list-group-flush d-none d-md-block ">
                <ul class="list-group-flush ps-0">
                    {% for item in cart_items %}
                    {% include 'checkout/includes/checkout_product_display.html' %}
                    {% endfor %}
                </ul>
            </li>
            <li class="p-font list-group-item text-primary fs-6 mx-0 mb-0 ps-0">
                <span class="float-start">{% trans 'Item Total' %}</span>
                <span class="float-end text-muted">€{{ cart_total }}</span>
            </li>
            {% if delivery != 0 %}
            <li class="p-font list-group-item text-primary fs-6 mx-0 mb-0 ps-0">
                <span class="float-start">{% trans 'Delivery' %}</span>
                <span class="float-end text-muted">€{{ delivery|floatformat:2 }}</span>
            </li>
            {% endif %}
            <li class="p-font list-group-item text-primary fs-6 mx-0 mb-0 ps-0">
                <strong><span class="p-font float-start">{% trans 'Grand Total' %}</span></strong>
                <strong><span class="float-end">€{{ grand_total }}</span></strong>
            </li>
        </ul>
        <p id="preloaderMessage"
            class="p-font d-none text-white position-absolute start-50 translate-middle text-center min-vw-100 min-vw-md-50 min-vw-lg-33 px-2">
            {% translate "Please do not refresh the page, press the back button or navigate away while the payment is processing.<br>Thank you for your patience."%}
        </p>
    </section>
</article>
{% else %}
<section class="row px-0 flex-xl-grow-1 px-md-2 bg-white">
    <article class="col text-center mt-4">
        <h2 class="p-font text-primary h4">{% trans 'Your cart is empty...' %}</h2>
        <h2 class="p-font text-primary mb-0">{% trans "Let's explore." %}</h2>
        <a class="p-font text-primary btn-tran btn btn-lg btn-warning shadow fw-bold my-4"
            href="{% url 'products:product-list' %}">
            {% trans 'Offerings' %}</a>
    </article>
</section>
<!--Script includes StripeElements scripts.-->
{% endif %}
{% endblock %}
{% block postloadjs %}
{{ block.super }}
{{ stripe_public_key|json_script:"id_stripe_public_key" }}
{{ client_secret|json_script:"id_client_secret" }}
<script src="{% static 'js/custom/stripeElements.js' %}?{{ VERSION }}" defer></script>
<script src="{% static 'js/custom/checkoutForm.js' %}?{{ VERSION }}"></script>
{% language 'en' %}
<script type="module">
    {% if request.session.cookie_consent == True %}
    checkoutPage({{ cart|safe }}, {{ cart_quantity }}, {{ cart_total|floatformat:2 }}, true)
    initiateCheckout({{ cart|safe }}, {{ cart_quantity }}, {{ cart_total|floatformat:2 }})
    {% else %}
    checkoutPage({{ cart|safe }}, {{ cart_quantity }}, {{ cart_total|floatformat:2 }}, false)
    {% endif %}
</script>
{% endlanguage %}
{% endblock %}

templates/checkout/order_list.html
{% extends 'base/base.html' %}
<!-- Loads internationalization -->
{% load i18n %} {% load static %}

<!-- Meta details -->
{% block meta_description %}{% trans 'Your orders. Thank you for your support.' %}{% endblock %}
{% block meta_keywords %}{{ block.super }} {% trans 'orders, finalized, paid, order history' %}{% endblock %}

<!--  Open Graph -->
{% block og_type %}website{% endblock %}
{% block og_title %}{% trans 'Ancient Wisdom, Modern Healing' %}{% endblock %}
{% block og_description %}{% trans 'Consciousness, spirituality, healing and ancestry. Working with systems such as Tarot, Oracle Cards, Shamanic Drumming and Healing. Creating events for sharing and connections between individuals and cultures.' %}{% endblock %}
{% block og_image %}{{request.scheme}}://{{request.META.HTTP_HOST}}{% static 'open_graph/logo1200x630.png' %}{% endblock %}
{% block og_image_type %}image/png{% endblock %}
{% block og_image_width %}1200{% endblock %}
{% block og_image_height %}630{% endblock %}
{% block og_image_alt %}{% trans 'Nuragic Shamanic Healing Logo' %}{% endblock %}
{% block head_title %}{% trans 'My Orders' %}{% endblock%}

{% block content %}
<!--Displays all orders that have been made in a list. -->
<section class="flex-grow-1 bg-white">
    <div class="row">
        <div class="col-12 bg-brown py-2">
            <h2 class="h-font l-space-2 text-white text-center text-uppercase display-4 mb-0">{% trans 'My Orders' %}
            </h2>
        </div>
    </div>
    <!-- Displays an order row for each item -->
    {% if orders %}
    <ul class="list-group list-group-flush p-2">
        {% for order in orders %}
        {% include 'checkout/includes/order_display.html' %}
        {% endfor %}
    </ul>
    {% else %}
    <section class="row px-0 flex-xl-grow-1 px-md-2 bg-white">
        <article class="col text-center mt-4">
            <h2 class="p-font text-primary h4">{% trans 'No Orders have been made'%}.</h2>
            <h2 class="p-font text-primary mb-0">{% trans 'What do we have for you' %}?</h2>
            <a class="p-font text-primary btn-tran btn btn-lg btn-warning shadow fw-bold my-4"
                href="{% url 'products:product-list' %}">{% trans 'Offerings' %}</a>
        </article>
    </section>
    {% endif %}
    {% if page_obj.has_next or page_obj.has_previous %}
    <nav aria-label="{% trans 'Product Page Navigation' %}">
        {% include 'base/includes/paginator.html' %}
    </nav>
    {% endif %}
</section>
{% endblock %}